Source Clickhouse: Fix exception in case `password` field is not provided in configuration (#10214)
* Fix exception in case password is not provided for Clickhouse source

Exception while checking connection:
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null

* Update changelog

* Bump version for Source Clickhouse

* Bump version of source-clickhouse-strict-encrypt

* Update version in docs

* correct conflict in docs

* bump connector version

* correct doc

Co-authored-by: Marcos Marx <marcosmarxm@gmail.com>