Kustomize: Missing NORMALIZATION_JOB_* environment variables in stable-with-resource-limits overlays (#17713)
The `NORMALIZATION_JOB_MAIN_CONTAINER*` environment variables (introduced in https://github.com/airbytehq/airbyte/commit/4d28000ae6caf01d981418f7a79ce8441e467de6 ) are missing in the `stable-with-resource-limits` k8s kustomize overlays which prevents `airbyte-worker` container from starting up. 
```
Error: couldn't find key NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST in ConfigMap <>/airbyte-env-....
```