Missing NORMALIZATION_JOB_* environment variables in stable-with-resource-limits overlays
The `NORMALIZATION_JOB_MAIN_CONTAINER*` environment variables (introduced in https://github.com/airbytehq/airbyte/commit/f8ebd4f60c3957a409a9f72b568b3ea55b74ad6a ) are missing in the `stable-with-resource-limits` k8s kustomize overlays which prevents `airbyte-worker` container from starting up. 
```
Error: couldn't find key NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST in ConfigMap <>/airbyte-env-....
```