Fix exception in case password is not provided for Clickhouse source
Exception while checking connection:
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at io.airbyte.integrations.source.clickhouse.ClickHouseSource.toDatabaseConfig(ClickHouseSource.java:98) ~[io.airbyte.airbyte-integrations.connectors-source-clickhouse-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:282) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createDatabase(AbstractJdbcSource.java:62) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.createDatabaseInternal(AbstractDbSource.java:490) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.check(AbstractDbSource.java:65) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:205) [io.airbyte.airbyte-integrations.bases-base-java-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:37) [io.airbyte.airbyte-integrations.bases-base-java-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102) [io.airbyte.airbyte-integrations.bases-base-java-0.35.1-alpha.jar:?]
        at io.airbyte.integrations.source.clickhouse.ClickHouseSource.main(ClickHouseSource.java:111) [io.airbyte.airbyte-integrations.connectors-source-clickhouse-0.35.1-alpha.jar:?]