🐛  [8783] Fix Broken HelmCharts v0.33.11 (#8784)
* [8783] Fix MinIO endpoint in HelmCharts

It was set as string but it is passed as an integer

* [8783] Pass the MinIO dependency required fields

It was throwing:

```shell
Error: UPGRADE FAILED: template: airbyte/charts/minio/templates/NOTES.txt:86:4: executing "airbyte/charts/minio/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredMinioPasswordErrors) "context" $)>: error calling include: template: airbyte/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
--
13-Dec-2021 23:20:47 | PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
13-Dec-2021 23:20:47 | Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
13-Dec-2021 23:20:47 | Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
13-Dec-2021 23:20:47 |
13-Dec-2021 23:20:47 | 'accessKey.password' must not be empty, please add '--set accessKey.password=$ACCESS_KEY' to the command. To get the current value:
13-Dec-2021 23:20:47 |
13-Dec-2021 23:20:47 | export ACCESS_KEY=$(kubectl get secret --namespace "data" airbyte-minio -o jsonpath="{.data.access-key}" \| base64 --decode)
13-Dec-2021 23:20:47 |
13-Dec-2021 23:20:47 | 'secretKey.password' must not be empty, please add '--set secretKey.password=$SECRET_KEY' to the command. To get the current value:
13-Dec-2021 23:20:47 |
13-Dec-2021 23:20:47 | export SECRET_KEY=$(kubectl get secret --namespace "data" airbyte-minio -o jsonpath="{.data.secret-key}" \| base64 --decode)
13-Dec-2021 23:20:47 |
13-Dec-2021 23:20:47 | Failed deploying Helm Chart!
```

when deploying the HelmChart with version 0.3.11.

* [8783] Bring back `webapp.ingress.hosts` to `README.md`

* Revert "[8783] Bring back `webapp.ingress.hosts` to `README.md`"

This reverts commit 2ad746ce470e5130f886aec3328d038fbeaa27bd.